name: Jekyll Build, Test and Deploy
on:
  push:
    branches: 
      - master
jobs:
  bundle-build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the sources
        uses: actions/checkout@v3
      - name: Set up Ruby, install and cache the bundle
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Build the site
        run: bundle exec jekyll build
      - name: Test the site
        run: bundle exec rake test
      - name: Cache the site
        id: cache-site
        uses: actions/cache@v3
        with:
          path: _site
          key: ${{ github.sha }}-site
  deploy:
    runs-on: ubuntu-latest
    needs: bundle-build-test
    steps:
      - name: Restore cache
        id: cache-site
        uses: actions/cache@v3
        with:
          path: _site
          key: ${{ github.sha }}-site
      - name: Something
        run: ls _site/
      - name: Delete cache
        env:
          PAT_CACHE: ${{ secrets.PAT_CACHE }}
        run: |
          curl -X DELETE \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token $PAT_CACHE" \
          https://api.github.com/repos/${{ github.repository }}/actions/caches/${{ github.sha }}-site
