name: Jekyll Build and Algolia index
on: workflow_dispatch
jobs:
  bundle-build-algolia:
    runs-on: ubuntu-latest
    env:
      ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Set up Ruby, install and cache bundle
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Build site
        run: bundle exec jekyll build
      - name: Index with Algolia
        run: bundle exec jekyll algolia --verbose
